import type { SpriteName } from '@/domain/content';

/**
 * Pixel sprites as character grids. Each character is a palette role
 * (see `PALETTE` in PixelSprite), `.` is transparent. Rows must be equal length.
 *
 *   X outline · F text · A accent · H accent-2 · S surface
 *   M muted · G gold · D danger · B deep background
 */
export type SpriteData = readonly string[];

export const ICONS: Record<SpriteName, SpriteData> = {
  rocket: [
    '.....XX.....',
    '....XSSX....',
    '...XSSSSX...',
    '...XSAASX...',
    '...XSAASX...',
    '...XSSSSX...',
    '..XXSSSSXX..',
    '.XHXSSSSXHX.',
    '.XHXXXXXXHX.',
    '.XX.XGGX.XX.',
    '....XGGX....',
    '.....XX.....',
  ],
  refactor: [
    '........XXX.',
    '.......XSSX.',
    '......XSSX..',
    '..X...XSSX.X',
    '..XX..XSSSXX',
    '...XXXSSSSX.',
    '....XSSSXX..',
    '...XSSSX....',
    '..XSSSX.....',
    '.XSSSX......',
    'XSSSX.......',
    'XXXX........',
  ],
  coin: [
    '....XXXX....',
    '..XXGGGGXX..',
    '.XGGGSSGGGX.',
    '.XGGGSSGGGX.',
    'XGGGGSSGGGGX',
    'XGGGGSSGGGGX',
    'XGGGGSSGGGGX',
    'XGGGGSSGGGGX',
    '.XGGGSSGGGX.',
    '.XGGGGGGGGX.',
    '..XXGGGGXX..',
    '....XXXX....',
  ],
  card: [
    'XXXXXXXXXXXX',
    'XHHHHHHHHHHX',
    'XXXXXXXXXXXX',
    'XHHHHHHHHHHX',
    'XHGGHHHHHHHX',
    'XHGGHHHHHHHX',
    'XHHHHHHHHHHX',
    'XHXXXHXXHHHX',
    'XHHHHHHHHHHX',
    'XXXXXXXXXXXX',
  ],
  chat: [
    'XXXXXXXXXXXX',
    'XSSSSSSSSSSX',
    'XSXXXXXXXXSX',
    'XSSSSSSSSSSX',
    'XSXXXXXXSSSX',
    'XSSSSSSSSSSX',
    'XXXSSXXXXXXX',
    '...XSX......',
    '...XX.......',
  ],
  chart: [
    'X...........',
    'X.........HH',
    'X.........HH',
    'X.....HH..HH',
    'X.....HH..HH',
    'X.HH..HH..HH',
    'X.HH..HH..HH',
    'X.HH..HH..HH',
    'XXXXXXXXXXXX',
  ],
  castle: [
    'X.X.X..X.X.X',
    'XXXXX..XXXXX',
    'XSSSX..XSSSX',
    'XSSSXXXXSSSX',
    'XSSSSSSSSSSX',
    'XSSXSSSSXSSX',
    'XSSSSSSSSSSX',
    'XSSSSXXSSSSX',
    'XSSSXHHXSSSX',
    'XSSSXHHXSSSX',
    'XXXXXXXXXXXX',
  ],
  shield: [
    '.XXXXXXXXXX.',
    'XHHHHHHHHHHX',
    'XHHSSHHHHHHX',
    'XHHSSHHHHHHX',
    'XHHHHHHHHHHX',
    'XHHHHHHHHHHX',
    '.XHHHHHHHHX.',
    '.XHHHHHHHHX.',
    '..XHHHHHHX..',
    '...XHHHHX...',
    '....XHHX....',
    '.....XX.....',
  ],
  bolt: [
    '......XXXX..',
    '.....XGGGX..',
    '....XGGGX...',
    '...XGGGX....',
    '..XGGGGXXXX.',
    '.XGGGGGGGGX.',
    '.XXXXGGGGX..',
    '....XGGGX...',
    '...XGGGX....',
    '..XGGGX.....',
    '..XGGX......',
    '..XXX.......',
  ],
  clock: [
    '...XXXXXX...',
    '..XSSSSSSX..',
    '.XSSSSXSSSX.',
    'XSSSSSXSSSSX',
    'XSSSSSXSSSSX',
    'XSSSSSXSSSSX',
    'XSSSSSXXXXSX',
    'XSSSSSSSSSSX',
    'XSSSSSSSSSSX',
    '.XSSSSSSSSX.',
    '..XSSSSSSX..',
    '...XXXXXX...',
  ],
  server: [
    'XXXXXXXXXXXX',
    'XSSSSSSSSASX',
    'XSXXXXXXSSSX',
    'XXXXXXXXXXXX',
    'XSSSSSSSSASX',
    'XSXXXXXXSSSX',
    'XXXXXXXXXXXX',
    'XSSSSSSSSASX',
    'XSXXXXXXSSSX',
    'XXXXXXXXXXXX',
    '..XX....XX..',
    '..XX....XX..',
  ],
  check: [
    '............',
    '..........XX',
    '.........XAX',
    '........XAX.',
    '.XX....XAX..',
    'XAAX..XAX...',
    '.XAAXXAX....',
    '..XAAAX.....',
    '...XAX......',
    '....X.......',
  ],
  mail: [
    'XXXXXXXXXXXX',
    'XXSSSSSSSSXX',
    'XSXSSSSSSXSX',
    'XSSXSSSSXSSX',
    'XSSSXXXXSSSX',
    'XSSSSSSSSSSX',
    'XSSSSSSSSSSX',
    'XXXXXXXXXXXX',
  ],
  telegram: [
    '..........XX',
    '........XXSX',
    '......XXSSSX',
    '....XXSSSSX.',
    '..XXSSSSSSX.',
    'XXSSSSXSSX..',
    '..XXSSXSSX..',
    '....XXXSX...',
    '.....XXSX...',
    '......XX....',
  ],
  linkedin: [
    'XXXXXXXXXXXX',
    'XAAAAAAAAAAX',
    'XASSAAAAAAAX',
    'XAAAAAAAAAAX',
    'XASSASSSSAAX',
    'XASSASSASSAX',
    'XASSASSASSAX',
    'XASSASSASSAX',
    'XAAAAAAAAAAX',
    'XXXXXXXXXXXX',
  ],
  github: [
    '.X........X.',
    '.XX......XX.',
    '.XXXXXXXXXX.',
    'XXXXXXXXXXXX',
    'XXSSXXXXSSXX',
    'XXSSXXXXSSXX',
    'XXXXXXXXXXXX',
    '.XXXXXXXXXX.',
    '..XXXXXXXX..',
    '...XX..XX...',
    '...XX..XX...',
  ],
  floppy: [
    'XXXXXXXXXXX.',
    'XHXSSSSSXHXX',
    'XHXSSSXSXHHX',
    'XHXSSSXSXHHX',
    'XHXXXXXXXHHX',
    'XHHHHHHHHHHX',
    'XHSSSSSSSSHX',
    'XHSXXXXXXSHX',
    'XHSSSSSSSSHX',
    'XHSXXXXXXSHX',
    'XHSSSSSSSSHX',
    'XXXXXXXXXXXX',
  ],
  star: [
    '.....XX.....',
    '.....XX.....',
    '....XGGX....',
    'XXXXGGGGXXXX',
    '.XGGGGGGGGX.',
    '..XGGGGGGX..',
    '...XGGGGX...',
    '..XGGXXGGX..',
    '..XGX..XGX..',
    '.XX......XX.',
  ],
  heart: [
    '.XX...XX.',
    'XDDX.XDDX',
    'XDDDXDDDX',
    'XDDDDDDDX',
    '.XDDDDDX.',
    '..XDDDX..',
    '...XDX...',
    '....X....',
  ],
  skull: [
    '..XXXXXXXX..',
    '.XSSSSSSSSX.',
    'XSSSSSSSSSSX',
    'XSXXSSSSXXSX',
    'XSXXSSSSXXSX',
    'XSSSSXXSSSSX',
    '.XSSSSSSSSX.',
    '..XSXSSXSX..',
    '..XXXXXXXX..',
  ],
  brain: [
    '...XXXXXX...',
    '..XHHXHHHX..',
    '.XHHHXHHHHX.',
    'XHXHHXHHXHHX',
    'XHHXHXHXHHHX',
    'XHHHHXHHHXHX',
    '.XHHXHHHHHX.',
    '..XHHXHHXX..',
    '...XXXXHX...',
    '......XHX...',
    '......XX....',
  ],
  database: [
    '..XXXXXXXX..',
    '.XSSSSSSSSX.',
    'XHSSSSSSSSHX',
    'XHHSSSSSSHHX',
    'XXHHHHHHHHXX',
    'XHXXXXXXXXHX',
    'XHHHHHHHHHHX',
    'XXHHHHHHHHXX',
    'XHXXXXXXXXHX',
    'XHHHHHHHHHHX',
    '.XHHHHHHHHX.',
    '..XXXXXXXX..',
  ],
  people: [
    '..XXX..XXX..',
    '.XSSSXXSSSX.',
    '.XSSSXXSSSX.',
    '.XSSSXXSSSX.',
    '..XXX..XXX..',
    '............',
    '.XXXX..XXXX.',
    'XHHHHXXHHHHX',
    'XHHHHXXHHHHX',
    'XHHHHXXHHHHX',
    'XXXXXXXXXXXX',
  ],
  chip: [
    '..X.X..X.X..',
    '..X.X..X.X..',
    'XXXXXXXXXXXX',
    '.XHHHHHHHHX.',
    'XXHXXXXXXHXX',
    '.XHXAAAAXHX.',
    'XXHXAAAAXHXX',
    '.XHXXXXXXHX.',
    'XXHHHHHHHHXX',
    'XXXXXXXXXXXX',
    '..X.X..X.X..',
    '..X.X..X.X..',
  ],
  cube: [
    '.....XX.....',
    '...XXSSXX...',
    '.XXSSSSSSXX.',
    'XSSSSSSSSSSX',
    'XHXXSSSSXXMX',
    'XHHHXXXXMMMX',
    'XHHHHHXMMMMX',
    'XHHHHHXMMMMX',
    'XHHHHHXMMMMX',
    '.XXHHHXMMXX.',
    '...XXHXXX...',
    '.....XX.....',
  ],
  cup: [
    '...X..X.....',
    '....X..X....',
    '...X..X.....',
    '............',
    'XXXXXXXXXX..',
    'XSSSSSSSSXXX',
    'XSSSSSSSSX.X',
    'XSSSSSSSSX.X',
    'XSSSSSSSSXXX',
    '.XSSSSSSX...',
    '..XXXXXX....',
    'XXXXXXXXXXX.',
  ],
};

/** Empty heart for language levels. */
export const HEART_EMPTY: SpriteData = [
  '.XX...XX.',
  'XBBX.XBBX',
  'XBBBXBBBX',
  'XBBBBBBBX',
  '.XBBBBBX.',
  '..XBBBX..',
  '...XBX...',
  '....X....',
];

/** Hero character — two walk frames (only the legs differ). */
const DEV_BODY = [
  '................',
  '.....XXXXXX.....',
  '....XHHHHHHX....',
  '...XHHHHHHHHX...',
  '...XHSSSSSSHX...',
  '...XSSXSSXSSX...',
  '...XSSXSSXSSX...',
  '...XSSSSSSSSX...',
  '....XSSXXSSX....',
  '.....XXXXXX.....',
  '...XXAAAAAAXX...',
  '..XAAXAAAAXAAX..',
  '..XAAXAAAAXAAX..',
  '..XSSXAAAAXSSX..',
];

export const DEV_FRAMES: readonly SpriteData[] = [
  [...DEV_BODY, '....XAAXXAAX....', '....XXX..XXX....'],
  [...DEV_BODY, '...XAAX..XAAX...', '...XXX....XXX...'],
];

export const MONITOR: SpriteData = [
  'XXXXXXXXXXXXXXXX',
  'XBBBBBBBBBBBBBBX',
  'XBAAABBBBBBBBBBX',
  'XBBBAAAAABBBBBBX',
  'XBBBAAABBBBBBBBX',
  'XBAABBBBBBBBBBBX',
  'XBBBAAAAAAABBBBX',
  'XBAAABBBBBBBBBBX',
  'XBBBBBBBBBBBBBBX',
  'XXXXXXXXXXXXXXXX',
  '......XXXX......',
  '....XXXXXXXX....',
];

export const CLOUD: SpriteData = [
  '.....XXXX.......',
  '...XXSSSSXX.....',
  '..XSSSSSSSSXXX..',
  '.XSSSSSSSSSSSSX.',
  'XSSSSSSSSSSSSSSX',
  '.XXXXXXXXXXXXXX.',
];

export const HILLS: SpriteData = [
  '..........XX....................',
  '........XXHHXX..................',
  '......XXHHHHHHXX.........XX.....',
  '....XXHHHHHHHHHHXX.....XXHHXX...',
  '..XXHHHHHHHHHHHHHHXX.XXHHHHHHXX.',
  'XXHHHHHHHHHHHHHHHHHHXHHHHHHHHHHX',
  'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
  'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
];

/** Enemy of every developer. */
export const BUG: SpriteData = [
  '.X....X.',
  '..XDDX..',
  'XXDDDDXX',
  '..DXXD..',
  'XXDDDDXX',
  '.X.XX.X.',
];
